### ISSUE TITLE
Errors downloading HTML files

### ISSUE THREAD

**Issue by ankenyr** [r0oth3x49/acloud-dl#92] opened 2022-03-04 00:01 UTC
This seems to only affect the html files of courses.

```
python3 acloud-dl.py -c cookie.txt -q 1080 -a
[*] : Lecture(s) : (2 of 2)
[*] : Downloading (002 Environment Setup)
[*] : 114.14MB/114.14MB 100.00% |##############################| 9.99MB/s
[+] : Downloaded  (002 Environment Setup)
[*] : Downloading asset(s)
[*] : Downloading (002 Terraform Pre-Compiled Binary.html)
[*] : Asset : '002 Terraform Pre-Compiled Binary.html' (download skipped).
[-] : URLError : either your internet connection is not working or server aborted the request
[*] : Downloading chapter : (2 of 6)
[+] : Chapter (02 Tips and Tricks)
[*] : Found (14) lectures ...
```

Not sure what logs I can provide here. Is this expected behavior?

**Comment by TheNamelessSir** [comment] 2022-04-30 16:42
Same here.

[*] : Asset : '002 Terraform Pre-Compiled Binary.html' (download skipped).
[-] : URLError : either your internet connection is not working or server aborted the request

All else is going smoothly, thanks for a great tool!

**Comment by anggapw** [comment] 2022-05-04 12:52
So, in my case

[*] : Asset : '004 Ansible Documentation.html' (download skipped).
[-] : Exception : 'NoneType' object has no attribute 'strip'

**Comment by fanuch** [comment] 2022-05-15 23:26
Have you had a look at what `002 Terraform Pre-Compiled Binary.html` is?
It's a link to the Terraform documentation -> https://www.terraform.io/downloads

That's why it doesn't work.

I would argue this isn't part of the course content so you can safely ignore the error.

**Comment by r0oth3x49** [comment] 2022-07-09 05:31
sorry for the late response. hope the issue is explained by @fanuch if not you can create a new issue closing this one

**Closed by r0oth3x49** 2022-07-09 05:31 UTC
