### ISSUE TITLE
Not download subtiles

### ISSUE THREAD

**Issue by voletri** [r0oth3x49/acloud-dl#79] opened 2021-09-07 11:41 UTC
Currently acloud-dl finished downloading the video but when I check in the video folder it doesn't see the subtile. Please help me!

**Comment by pkasperek** [comment] 2021-12-07 06:08
Hi,

I fixed this bug in my fork of this repo:  https://github.com/pkasperek/acloud-dl . I Send to owner of this project information about my changes and possibility merge request, but I hvan't been response :(.

**Comment by YogeshPuranik** [comment] 2021-12-18 20:38
@pkasperek  @r0oth3x49  - I am not able to understand how to copy the header from the network element (from the Inspect) and neither I could get option of GET from the course browser. Please help on below points 

1. Now click on Browse Courses in the acloud.guru navbar and refresh the page you will see some requests under Network T
Right click on any of the Requests which links to acloud.guru. Simply copy Request Headers and save to text file.
Done run the acloud-dl against that text file it will start downloading the course.

2. Move mouse to the course you want to download.
On mouseover you will see a button "GET" click on that.
It Will redirect to the course there is another button "START THIS COURSE" click on that.
Done, Now you can use the below usage.

I have to download videos of acloudguru to refer it offline my subscription is getting ended in 2 days.Thanks a lot in advance.

**Comment by r0oth3x49** [comment] 2021-12-30 05:43
the issue is fixed with recent PR merge, if not re-open the issue.

**Closed by r0oth3x49** 2021-12-30 05:43 UTC
