### ISSUE TITLE
Can't Download with mp4 extension

### ISSUE THREAD

**Issue by silverbret1709** [r0oth3x49/acloud-dl#83] opened 2021-10-05 00:21 UTC
I downloaded acloud with the newest version
but video files don't have mp4 extensions
Please help me
![Screenshot 2021-10-04 202056](https://user-images.githubusercontent.com/13728194/135941627-d22f5106-07b8-429f-bc87-db5e22d7866b.png)

**Comment by queen4me** [comment] 2021-12-09 19:12
I have the same problem and I have a valid ACG account.

**Comment by r0oth3x49** [comment] 2021-12-30 05:41
the issue is fixed now with the recent PR merge if not you can re-open this issue.

**Closed by r0oth3x49** 2021-12-30 05:41 UTC
Labels: bug, account needed
