### ISSUE TITLE
Error after downloading 2 files

### ISSUE THREAD

**Issue by queen4me** [r0oth3x49/acloud-dl#106] opened 2023-05-10 15:08 UTC
I'm using Windows 10 with freshly installed Python/PiP.
Every download starts but after downloading the first two files the download stops and the program ends with:

Traceback (most recent call last):
  File "C:\PYTHON\acloud\acloud-dl.py", line 408, in <module>
    main()
  File "C:\PYTHON\acloud\acloud-dl.py", line 396, in main
    cloud_guru.course_download(path=options.output, quality=options.quality,
  File "C:\PYTHON\acloud\acloud-dl.py", line 295, in course_download
    self.download_lectures_only(lecture_best=lecture_best, lecture_title=lecture_title,
  File "C:\PYTHON\acloud\acloud-dl.py", line 217, in download_lectures_only
    self.download_subtitles(subtitle=lecture_subs, filepath=filepath)
  File "C:\PYTHON\acloud\acloud-dl.py", line 148, in download_subtitles
    self.convert(filename=filename)
  File "C:\PYTHON\acloud\acloud\_vtt2srt.py", line 106, in convert
    timecode = self._generate_timecode(seq, unescapeHTML(line))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PYTHON\acloud\acloud\_vtt2srt.py", line 79, in _generate_timecode
    match = re.match(self._TIMECODE, timecode, flags=re.U)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 166, in match
    return _compile(pattern, flags).match(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\re\_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\re\_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\re\_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\re\_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 63

**Comment by rabin-io** [comment] 2023-05-10 20:10
Try using my branch https://github.com/r0oth3x49/acloud-dl/pull/104

**Comment by queen4me** [comment] 2023-05-11 15:08
Thanks for your reply but how do I have to use your branch?
I'm not github expert and just downloaded your code and was happy to get it running with Python on my windows system.

**Comment by rabin-io** [comment] 2023-05-12 15:55
Clone my repo, and checkout the fix branch,

```sh
git clone https://github.com/rabin-io/acloud-dl.git
cd acloud-dl
git checkout fix-issue-103
```

or just download the branch directly https://github.com/rabin-io/acloud-dl/archive/refs/heads/fix-issue-103.zip

**Comment by queen4me** [comment] 2023-05-12 16:37
Thank you so much for the link to the branch.
Working again now like a charm.

**Comment by r0oth3x49** [comment] 2023-06-27 14:50
@queen4me the issue is resolved with PR from @rabin-io so closing this

**Closed by r0oth3x49** 2023-06-27 14:50 UTC
