### ISSUE TITLE
Error occured for some chapters

### ISSUE THREAD

**Issue by chimpa** [r0oth3x49/acloud-dl#32] opened 2020-04-10 07:08 UTC
Following error happens when using this python script.
'NoneType' object has no attribute 'strip'

This happened when trying to download "Introduction to Ansible" course.

**Comment by r0oth3x49** [comment] 2020-04-12 08:44
@chimpa can you share more info? i can't reproduce the error.

**Comment by neoluu** [comment] 2020-04-12 13:04
I've also gotten the same error with same course and some others:

[*] : Downloading asset(s)
[*] : Downloading (004 My Coke Rewards Case Study.html)
[*] : Asset : '004 My Coke Rewards Case Study.html' (download skipped).
[-] : Exception : 'NoneType' object has no attribute 'strip'

**Comment by r0oth3x49** [comment] 2020-04-24 19:14
no updates closing the closing the issue.

**Closed by r0oth3x49** 2020-04-24 19:14 UTC
Labels: account needed, question
